//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakturaNummer
    {
        public int faktura_id { get; set; }
        public Nullable<int> medlems_id { get; set; }
        public Nullable<int> kontigent_id { get; set; }
    
        public virtual Kontigent Kontigent { get; set; }
        public virtual MedlemKonto MedlemKonto { get; set; }
    }
}
