//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedlemKonto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedlemKonto()
        {
            this.FakturaNummer = new HashSet<FakturaNummer>();
        }
    
        public int medlems_id { get; set; }
        public string medlems_fornavn { get; set; }
        public string medlems_efternavn { get; set; }
        public string medlems_foedselsdag { get; set; }
        public string medlems_adress { get; set; }
        public Nullable<int> zipcode_zipcode { get; set; }
        public Nullable<int> medlems_telefon { get; set; }
        public string medlems_mail { get; set; }
        public bool betalt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FakturaNummer> FakturaNummer { get; set; }
        public virtual PostNummer PostNummer { get; set; }
    }
}
